spring:
  application:
    name: Hospital-Management-System

  datasource:
    url: jdbc:postgresql://localhost:5432/hospital_management_db
    username: postgres
    password: 831800
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

server:
  port: 8181
  servlet:
    context-path: /api/v1.0
